name: Tests
on: push

jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup python
              uses: actions/setup-python@v2
              with:
                python-version: 3.11.3

            - name: Test with unittest
              run: python3 -m unittest test_cities.py